GET http://localhost:5000/login

###

POST http://localhost:5000/register
Content-Type: application/json

{
    "username":"mohannad1",
    "email": "hannodi.di@gmail.com",
    "password": "123456789"
}


###

POST http://localhost:5000/login

Content-Type: application/json

{
    "email": "hannodi.di@gmail.com",
    "password": "12345678"
}

###
GET http://localhost:5000/users

